version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'
